#!/bin/bash

echo 'Set permissions'

chown w3data:w3data -R /usr/share/letsgo-1.0-3
chown w3data:w3data -R /var/www/letsgo

touch /var/log/uwsgi.log
touch /var/log/uwsgi-letsgo.log

chown w3data:w3data /etc/uwsgi/letsgo.yaml

chown w3data:w3data /var/log/uwsgi.log
chown w3data:w3data /var/log/uwsgi-letsgo.log

chmod 755 /usr/share/letsgo-1.0-3
chown 755 /var/www/letsgo

echo 'Start migrations'
su w3data -c "python3.4 /usr/share/letsgo-1.0-2/manage.py migrate"

echo 'Restart services'
service nginx restart
su w3data -c "/usr/bin/uwsgi --yaml /etc/uwsgi/letsgo.yaml"
